WebApplication7/Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication7.Models
{
    public class City
    {
        [Key]
        public int city_id { get; set; }

        [Required]
        [Display(Name = "City Name")]
        public string city_name { get; set; }

        [Required]
        [Display(Name = "Province")]
        public string province { get; set; }

    }
}

WebApplication7/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication7.Models;

namespace WebApplication7.Controllers
{
    public class CitiesController : Controller
    {
        private WebApplication7Context db = new WebApplication7Context();

        // GET: Cities
        public ActionResult Index(string SearchName, string Province)
        {
            //Search by province
            var provinceList = new List<string>();
            var provinceQuery = from p in db.Cities orderby p.province select p.province;

            provinceList.AddRange(provinceQuery.Distinct());
            ViewBag.Province = new SelectList(provinceList);

            //Search by name
            var Cities = from city in db.Cities select city;
            //Search by name
            if (!String.IsNullOrEmpty(SearchName))
            {
                Cities = Cities.Where(x => x.city_name.Contains(SearchName));
            }

            //Search by province
            if (!String.IsNullOrEmpty(Province))
            {
                Cities = Cities.Where(x => x.province.Contains(Province));
            }

            return View(Cities);
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "city_id,city_name,province")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "city_id,city_name,province")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

WebApplication7/Views/Cities/Create.cshtml
@model WebApplication7.Models.City

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.city_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.province, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.province, new List<SelectListItem>
                    {
                    new SelectListItem { Value = "Kwa-Zulu Natal" , Text = "Kwa-Zulu Natal" },
                    new SelectListItem { Value = "Gauteng" , Text = "Gauteng" },
                    new SelectListItem { Value = "Free State" , Text = "Free State" },
                    new SelectListItem { Value = "Mpumalanga" , Text = "Mpumalanga" },
                    new SelectListItem { Value = "Northern Cape" , Text = "Northern Cape" },
                    new SelectListItem { Value = "Western Cape" , Text = "Western Cape" },
                    new SelectListItem { Value = "Eastern Cape" , Text = "Eastern Cape" },
                    new SelectListItem { Value = "Limpopo" , Text = "Limpopo" },
                    new SelectListItem { Value = "North West" , Text = "North West" }
                    }
                   ,"Select Province",  htmlAttributes : new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.province, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/Views/Cities/Delete.cshtml
@model WebApplication7.Models.City

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.city_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.city_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.province)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.province)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication7/Views/Cities/Details.cshtml
@model WebApplication7.Models.City

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.city_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.city_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.province)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.province)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.city_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication7/Views/Cities/Edit.cshtml
@model WebApplication7.Models.City

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.city_id)

        <div class="form-group">
            @Html.LabelFor(model => model.city_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.province, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.province, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.province, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/Views/Cities/Index.cshtml
@model IEnumerable<WebApplication7.Models.City>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Cities", FormMethod.Get))
{
    <p>
        <hr />
        City Name: @Html.TextBox("SearchName")
        <br /><br />
        <b>Filter by:</b>
        <br />
        Province: @Html.DropDownList("Province", "All")
        <br /> <br />
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.city_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.province)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.city_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.province)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.city_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.city_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.city_id })
            </td>
        </tr>
    }
</table>

</table>