WebApplication7/Models/Beach.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication7.Models
{
    public class Beach
    {
        
            [Key]
            public int beach_id { get; set; }

            [Required]
            [Display(Name = "Beach Name")]
            public string beach_name { get; set; }

            [Display(Name = "City Name")]
            public int city_id { get; set; }

            [ForeignKey("city_id")]
            public City city { get; set; }
        
    }
}

WebApplication7/Controllers/BeachesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication7.Models;

namespace WebApplication7.Controllers
{
    public class BeachesController : Controller
    {
        private WebApplication7Context db = new WebApplication7Context();

        // GET: Beaches
        public ActionResult Index(string SearchName, string Beach)
        {
            //Search by city
            var cityList = new List<string>();
            var cityQuery = from b in db.Beaches orderby b.city.city_name select b.city.city_name;

            cityList.AddRange(cityQuery.Distinct());
            ViewBag.Beach = new SelectList(cityList);

            //Search by name
            var Beaches = from beach in db.Beaches select beach;

            //includes city
            Beaches = db.Beaches.Include(b => b.city);


            //Search by beach name
            if (!String.IsNullOrEmpty(SearchName))
            {
                Beaches = Beaches.Where(x => x.beach_name.Contains(SearchName));
            }

            //Search by City
            if (!String.IsNullOrEmpty(Beach))
            {
                Beaches = Beaches.Where(x => x.city.city_name.Contains(Beach));
            }


            return View(Beaches);
        }

        // GET: Beaches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beach beach = db.Beaches.Find(id);
            if (beach == null)
            {
                return HttpNotFound();
            }
            return View(beach);
        }

        // GET: Beaches/Create
        public ActionResult Create()
        {
            ViewBag.city_id = new SelectList(db.Cities, "city_id", "city_name");
            return View();
        }

        // POST: Beaches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "beach_id,beach_name,city_id")] Beach beach)
        {
            if (ModelState.IsValid)
            {
                db.Beaches.Add(beach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.city_id = new SelectList(db.Cities, "city_id", "city_name", beach.city_id);
            return View(beach);
        }

        // GET: Beaches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beach beach = db.Beaches.Find(id);
            if (beach == null)
            {
                return HttpNotFound();
            }
            ViewBag.city_id = new SelectList(db.Cities, "city_id", "city_name", beach.city_id);
            return View(beach);
        }

        // POST: Beaches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "beach_id,beach_name,city_id")] Beach beach)
        {
            if (ModelState.IsValid)
            {
                db.Entry(beach).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.city_id = new SelectList(db.Cities, "city_id", "city_name", beach.city_id);
            return View(beach);
        }

        // GET: Beaches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beach beach = db.Beaches.Find(id);
            if (beach == null)
            {
                return HttpNotFound();
            }
            return View(beach);
        }

        // POST: Beaches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Beach beach = db.Beaches.Find(id);
            db.Beaches.Remove(beach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication7/Views/Beaches/Create.cshtml
@model WebApplication7.Models.Beach

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Beach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.beach_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.beach_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.beach_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city_id, "city_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("city_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.city_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/Views/Beaches/Delete.cshtml
@model WebApplication7.Models.Beach

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Beach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.city.city_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city.city_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.beach_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.beach_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication7/Views/Beaches/Details.cshtml
@model WebApplication7.Models.Beach

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Beach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.city.city_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city.city_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.beach_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.beach_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.beach_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication7/Views/Beaches/Edit.cshtml
@model WebApplication7.Models.Beach

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Beach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.beach_id)

        <div class="form-group">
            @Html.LabelFor(model => model.beach_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.beach_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.beach_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city_id, "city_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("city_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.city_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/Views/Beaches/Index.cshtml
@model IEnumerable<WebApplication7.Models.Beach>

@{
    ViewBag.Title = "Index";
}

@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Beaches", FormMethod.Get))
{
    <p>
        <hr />
        Beach name: @Html.TextBox("SearchName")
        <br /><br />
        <b>Filter by: </b>
        <br />
        City: @Html.DropDownList("Beach", "All")
        <br /><br />
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.city.city_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.beach_name)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.city.city_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.beach_name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.beach_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.beach_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.beach_id })
            </td>
        </tr>
    }
</table>