WebApplication7/Models/Lifeguard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace WebApplication7.Models
{
    public class Lifeguards
    {
        [Key]
        public int lifeguard_id { get; set; }

        [Required]
        [Display(Name = "Lifeguard Name")]
        [MaxLength(50)]
        public string lifeguard_name { get; set; }

        [Required]
        [Display(Name = "Date Of birth")]
        [DataType(DataType.Date)]
        public DateTime DOB { get; set; }

        [Required]
        [Display(Name = "Gender")]
        public string Gender { get; set; }

        [Required]
        [Display(Name = "Lifeguard status")]
        public string l_status { get; set; }

        [Display(Name = "City Name")]
        public int city_id { get; set; }
        [ForeignKey("city_id")]
        public City city { get; set; }

    }
}

WebApplication7/Controllers/LifeguardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication7.Models;

namespace WebApplication7.Controllers
{
    public class LifeguardsController : Controller
    {
        private WebApplication7Context db = new WebApplication7Context();

        // GET: Lifeguards
        public ActionResult Index(string SearchName, string City, string Gender, String Status)
        {
            //Search by city
            var cityList = new List<string>();
            var cityQuery = from c in db.Lifeguards orderby c.city.city_name select c.city.city_name;

            cityList.AddRange(cityQuery.Distinct());
            ViewBag.City = new SelectList(cityList);

            //Search by Gender
            var genderList = new List<string>();
            var genderQuery = from g in db.Lifeguards orderby g.Gender select g.Gender;

            genderList.AddRange(genderQuery.Distinct());
            ViewBag.Gender = new SelectList(genderList);

            //Search by Status
            var statusList = new List<string>();
            var statusQuery = from s in db.Lifeguards orderby s.l_status select s.l_status;

            statusList.AddRange(statusQuery.Distinct());
            ViewBag.Status = new SelectList(statusList);

            //Search by name
            var lifeguards = from lg in db.Lifeguards select lg;

            //includes city 
            lifeguards = db.Lifeguards.Include(l => l.city);

            //Search by name
            if (!String.IsNullOrEmpty(SearchName))
            {
                lifeguards = lifeguards.Where(x => x.lifeguard_name.Contains(SearchName));
            }

            //Search by City
            if (!String.IsNullOrEmpty(City))
            {
                lifeguards = lifeguards.Where(x => x.city.city_name == City);
            }

            //Search by gender
            if (!String.IsNullOrEmpty(Gender))
            {
                lifeguards = lifeguards.Where(x => x.Gender == Gender);
            }

            //Search by Status
            if (!String.IsNullOrEmpty(Status))
            {
                lifeguards = lifeguards.Where(x => x.l_status == Status);
            }



            return View(lifeguards);
        }

        // GET: Lifeguards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lifeguards lifeguards = db.Lifeguards.Find(id);
            if (lifeguards == null)
            {
                return HttpNotFound();
            }
            return View(lifeguards);
        }

        // GET: Lifeguards/Create
        public ActionResult Create()
        {
            ViewBag.city_id = new SelectList(db.Cities, "city_id", "city_name");
            return View();
        }

        // POST: Lifeguards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "lifeguard_id,lifeguard_name,DOB,Gender,l_status,city_id")] Lifeguards lifeguards)
        {
            if (ModelState.IsValid)
            {
                db.Lifeguards.Add(lifeguards);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.city_id = new SelectList(db.Cities, "city_id", "city_name", lifeguards.city_id);
            return View(lifeguards);
        }

        // GET: Lifeguards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lifeguards lifeguards = db.Lifeguards.Find(id);
            if (lifeguards == null)
            {
                return HttpNotFound();
            }
            ViewBag.city_id = new SelectList(db.Cities, "city_id", "city_name", lifeguards.city_id);
            return View(lifeguards);
        }

        // POST: Lifeguards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "lifeguard_id,lifeguard_name,DOB,Gender,l_status,city_id")] Lifeguards lifeguards)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lifeguards).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.city_id = new SelectList(db.Cities, "city_id", "city_name", lifeguards.city_id);
            return View(lifeguards);
        }

        // GET: Lifeguards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lifeguards lifeguards = db.Lifeguards.Find(id);
            if (lifeguards == null)
            {
                return HttpNotFound();
            }
            return View(lifeguards);
        }

        // POST: Lifeguards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lifeguards lifeguards = db.Lifeguards.Find(id);
            db.Lifeguards.Remove(lifeguards);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication7/Views/Lifeguards/Create.cshtml
@model WebApplication7.Models.Lifeguards
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Lifeguards</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.lifeguard_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lifeguard_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lifeguard_name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" }, Type = "date" })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Gender, "Male", new { htmlAttributes = new { @class = "form-control" } }) Male<br />
                @Html.RadioButtonFor(model => model.Gender, "Female", new { htmlAttributes = new { @class = "form-control" } }) Female<br />
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.l_status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.l_status, "Active", new { htmlAttributes = new { @class = "form-control" } }) Active<br />
                @Html.RadioButtonFor(model => model.l_status, "Inactive", new { htmlAttributes = new { @class = "form-control" } }) Inactive<br />
                @Html.ValidationMessageFor(model => model.l_status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.city_id, "city_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("city_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.city_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/Views/Lifeguards/Delete.cshtml
@model WebApplication7.Models.Lifeguards

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lifeguards</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.city.city_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.city.city_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.lifeguard_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.lifeguard_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.l_status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.l_status)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication7/Views/Lifeguards/Details.cshtml
@model WebApplication7.Models.Lifeguards

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div>
    <h4>Lifeguards</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.city.city_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.city.city_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.lifeguard_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.lifeguard_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.l_status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.l_status)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.lifeguard_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication7/Views/Lifeguards/Edit.cshtml
@model WebApplication7.Models.Lifeguards

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Lifeguards</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.lifeguard_id)
        <div class="form-group">
            @Html.LabelFor(model => model.lifeguard_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lifeguard_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lifeguard_name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.l_status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.l_status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.l_status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.city_id, "city_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("city_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.city_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/Views/Lifeguards/Index.cshtml
@model IEnumerable<WebApplication7.Models.Lifeguards>
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Lifeguards", FormMethod.Get))
{
    <p>
        <hr />
        Lifeguard name: @Html.TextBox("SearchName")
        <br /> <br />
        <b>Filter by: </b>
        <br />
        City: @Html.DropDownList("City", "All")
        Gender: @Html.DropDownList("Gender", "All")
        Status: @Html.DropDownList("Status", "All")
        <br /> <br />
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.city.city_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lifeguard_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.l_status)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.city.city_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lifeguard_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.l_status)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.lifeguard_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.lifeguard_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.lifeguard_id })
            </td>
        </tr>
    }
</table>